// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hSe7QK2lFvUQLvelHa3q_2Fy-SEwI0o',
    appId: '1:805014059706:web:373a7404b62ede165f6083',
    messagingSenderId: '805014059706',
    projectId: 'webrtc-test-52b42',
    authDomain: 'webrtc-test-52b42.firebaseapp.com',
    storageBucket: 'webrtc-test-52b42.appspot.com',
    measurementId: 'G-D8CF615ME7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZdwKii5so-prRxGPxTv4TUAFUrOujBo',
    appId: '1:805014059706:android:f58765c1abbf2f7b5f6083',
    messagingSenderId: '805014059706',
    projectId: 'webrtc-test-52b42',
    storageBucket: 'webrtc-test-52b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChfa6DaZD86yNGaKRGXwAV5h7Vlzfre88',
    appId: '1:805014059706:ios:d6fa0528d07126ae5f6083',
    messagingSenderId: '805014059706',
    projectId: 'webrtc-test-52b42',
    storageBucket: 'webrtc-test-52b42.appspot.com',
    iosClientId: '805014059706-7c8n8so07olg9lcv3co53f2d90s8k592.apps.googleusercontent.com',
    iosBundleId: 'com.example.webRtcDemo',
  );
}
